export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SHOW_INGREDIENTS = 'SHOW_INGREDIENTS';
export const SHOW_ALLERGEN = 'SHOW_ALLERGEN';
export const REMOVE_ALLERGEN = 'REMOVE_ALLERGEN';
export const HANDLE_PARTS = 'HANDLE_PARTS';
export const VALIDATE = 'VALIDATE';
export const GET_UNIT = 'GET_UNIT';

export const USE_COMPANY = 'USE_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const TOGGLE_COMPANIES = 'TOGGLE_COMPANIES';
export const HANDLE_CHANGE_COMPANY = 'HANDLE_CHANGE_COMPANY';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';

export const HANDLE_NUTRIENT = 'HANDLE_NUTRIENT';
