export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SHOW_INGREDIENTS = 'SHOW_INGREDIENTS';
export const SHOW_ALLERGEN = 'SHOW_ALLERGEN';
export const REMOVE_ALLERGEN = 'REMOVE_ALLERGEN';
export const HANDLE_PARTS = 'HANDLE_PARTS';
export const VALIDATE = 'VALIDATE';
